### ISSUE TITLE
Running mysql_secure_installation will not work

### ISSUE THREAD

**Issue by rockts** [digitoimistodude/macos-lemp-setup#2]
![2018-09-28 22 35 58](https://user-images.githubusercontent.com/9766196/46215027-f344ee80-c36e-11e8-8a1a-f05a3a197a1a.png)

Entering any password will prompt this error.

**Comment by rollecode** [comment]
Press enter. There is none.

**Comment by rockts** [comment]
No, or ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

**Comment by rollecode** [comment]
Is MySQL running? Did you run setup properly? Do you have any other development environments set up prior this? Double check MySQL installation instructions and reach out for help for example [from here](https://stackoverflow.com/questions/5376427/cant-connect-to-local-mysql-server-through-socket-var-mysql-mysql-sock-38).

**Comment by rockts** [comment]
Thank you, buddy.

**Comment by rollecode** [comment]
No probs!

**Comment by rockts** [comment]
Are you buddy, my mysql is still a bit problematic. Can you help me?

**Comment by rollecode** [comment]
Can you be more specific? We are not really a MySQL/Linux support, but I can try to help if you tell more about your problem.

**Comment by rockts** [comment]
Sorry, my buddy is disturbing and the problem is solved. But still thank you

**Comment by rollecode** [comment]
We have this issue on another machine. In what way did you get it solved @rockts?
