### ISSUE TITLE
Deprecated taps.

### ISSUE THREAD

**Issue by uhlhosting** [digitoimistodude/macos-lemp-setup#6]
Deprecated brew taps:

brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
same for nginx tap in use. check logs.

**Comment by rollecode** [comment]
Thank you for taking the time to open an issue. Can you elaborate what is your issue with the package exactly? Please include the erroneous output.

**Comment by uhlhosting** [comment]
Updating Homebrew...
Error: homebrew/dupes was deprecated. This tap is now empty and all its contents were either deleted or migrated.
Updating Homebrew...
Error: homebrew/versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
Updating Homebrew...

**Comment by uhlhosting** [comment]
```
21:26:53 [cosmic:~] 3s % brew services 
Name           Status  User Plist
dnsmasq        error   root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
docker-machine error   root /Library/LaunchDaemons/homebrew.mxcl.docker-machine.plist
libvirt        started root /Library/LaunchDaemons/homebrew.mxcl.libvirt.plist
mariadb        started root /Library/LaunchDaemons/homebrew.mxcl.mariadb.plist
nginx          error   root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php            error   root /Library/LaunchDaemons/homebrew.mxcl.php.plist
unbound        error   root /Library/LaunchDaemons/homebrew.mxcl.unbound.plist
21:26:57 [cosmic:~] 3s % brew services

```

**Comment by rollecode** [comment]
Try `brew untap homebrew/dupes` and others, then uninstall nginx, mariadb and php packages. They may have been migrated to core. I'll investigate this when I have more time, this seems fairly common issue based on a quick GitHub search. In the meantime you can suggest edits or even send a PR that fixes this.

**Comment by rollecode** [comment]
It seems this has resolved itself, tested on Macbook Pro M1 today. Please send a PR if you still think this is an issue.
